### ISSUE TITLE
不懂就问，这个项目是做什么的

### ISSUE THREAD

**Issue by CALLMELARE** [YunYouJun/evil-eye#1]

**Comment by YunYouJun** [comment]
只是一个刚刚开坑的项目，还没有任何实质进展，最终目的成果是在浏览器端通过摄像头检测出人眼视线的关注点。

譬如说放一张图，左边是大姐姐右边是新款游戏机，监测出人们第一眼的视线会停留在哪里。

当然后续内容随时会发生变化。

**Comment by CALLMELARE** [comment]
好耶
